# Generated by Django 5.2.4 on 2025-07-16 04:08

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total rows to process')),
                ('processed_rows', models.PositiveIntegerField(default=0, help_text='Rows processed so far')),
                ('successful_rows', models.PositiveIntegerField(default=0, help_text='Successfully processed rows')),
                ('failed_rows', models.PositiveIntegerField(default=0, help_text='Failed rows')),
                ('error_details', models.JSONField(blank=True, default=list, help_text='List of errors encountered')),
                ('file_name', models.CharField(blank=True, help_text='Original filename', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_id', models.CharField(help_text='NGO identifier', max_length=100)),
                ('month', models.CharField(help_text='Report month in YYYY-MM format', max_length=7)),
                ('people_helped', models.PositiveIntegerField(help_text='Number of people helped this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('events_conducted', models.PositiveIntegerField(help_text='Number of events conducted this month', validators=[django.core.validators.MinValueValidator(0)])),
                ('funds_utilized', models.DecimalField(decimal_places=2, help_text='Amount of funds utilized this month', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('ngo_id', 'month')},
            },
        ),
    ]
